# Script to create Figure 4, Figure H, Figure I and Figure 5
# 2024-10-28, Ifremer 
# Depends on dataset death_predicted.csv generated by script 2_National_Data_mytilus.R

# Install necessary libraries and load it
list.of.packages <- c("tidyverse", "viridis","GGally","scales")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(tidyverse)
library(viridis)
library(scales)

###################################################################################################
############################## Mortality Metrics #################################################

# Data predicted loading: 
death_preds <- read.csv(file.path("Data","new_datasets","death_predicted.csv"), header=TRUE, sep=",")
death_preds<-death_preds %>% mutate(id_site = as.factor(id_site), Campaign = as.factor(Campaign)) 

# Maximum mortality (MM)
death_preds261 <- death_preds %>%
  filter(DOY == "261") %>%
  rename("MM" = "CM_pred")

# Figure 4 : This is the figure 4 which is included in the datapaper
Fig4 <- ggplot(death_preds261, aes(x = reorder(id_site, as.numeric(id_site)), y = reorder(Campaign, as.integer(as.character(Campaign))) , fill = MM)) +
  geom_raster() +
  coord_fixed() +
  theme(panel.background = element_rect(fill = "white", colour = "black", linewidth = 0.5, linetype = "solid"),
        legend.position = "top",  
        plot.margin = unit(c(0, 0, 0, 0), "null")
  )+
  guides(
    fill = guide_colourbar(
      title.position = "top", title.hjust = 0.5, frame.colour = "black", barwidth = 12,
      barheight = 1, order = 1,
      direction = "horizontal",  
      label.position = "bottom",  
      label.hjust = 0.5,  
      title.vjust = 1  
    )
  ) +
  ylab("Campaign") +
  xlab("Site") +
  scale_fill_viridis(name = "Cumulative mortality predicted", direction = -1)
ggsave(Fig4, file = file.path("Figures","Figure4.jpeg"),
       width = 8.6, height = 6, dpi = 300, units = "in",
       type = "cairo")

# Mortality initiation :
mortality_initiation <- death_preds %>%
  group_by(Campaign, id_site) %>%
  mutate(MI = max(CM_pred) / 10) %>%
  filter(CM_pred > MI) %>%
  summarize(MI = min(DOY)) %>% 
  ungroup()

#Figure H (this figure is not included in the article):
FigH <- ggplot(mortality_initiation, aes(x = reorder(Campaign, as.integer(as.character(Campaign))), y = reorder(id_site, as.numeric(id_site)), fill = MI)) +
  geom_raster() +
  coord_fixed() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.background = element_rect(fill = "white", colour = "black", linewidth = 0.5, linetype = "solid"),
        legend.position = "top",  
        plot.margin = unit(c(0, 0, 0, 0), "null")
  )+
  guides(
    fill = guide_colourbar(
      title.position = "top", title.hjust = 0.5, frame.colour = "black", barwidth = 12,
      barheight = 1, order = 1,
      direction = "horizontal",  
      label.position = "bottom",  
      label.hjust = 0.5,  
      title.vjust = 1  
    )
  ) +
  ylab("Site") +
  xlab("Campaign") +
  scale_fill_viridis(name = "Mortality initiation", direction = -1)
ggsave(FigH, file = file.path("Figures","FigureH.jpeg"),
       width = 19.2, height = 11.77, dpi = 300, units = "in",
       type = "cairo")

# Alpha metric :
#Line between the initiation of mortality (MI) and maximum mortality at day 261 (MM) : 
T1<- death_preds %>%
  group_by(Campaign, id_site) %>%
  mutate(mort_10 = max(CM_pred) / 10)
T1<-T1%>% group_by(Campaign, id_site)%>%filter(CM_pred > mort_10)
T1<-T1%>%group_by(Campaign, id_site)%>%filter(DOY==min(DOY))
T1<-T1%>%dplyr::select(Campaign,id_site,DOY,CM_pred)

T2<-death_preds261%>%
  rename("CM_pred"="MM")

Line<-rbind(T1,T2)

# Function to calculate the slope :
calculate_slope <- function(x, y) {
  model <- lm(y ~ x)
  return(coef(model)[2])  
}

# Applying the function by group (Campaign x id_site)
Alpha <- Line %>%
  group_by(Campaign, id_site) %>%
  summarise(alpha = calculate_slope(DOY, CM_pred))

#Figure I (this figure is not included in the article):
FigI <- ggplot(Alpha, aes(x = reorder(Campaign, as.integer(as.character(Campaign))), y = reorder(id_site, as.numeric(id_site)), fill = alpha)) +
  geom_raster() +
  coord_fixed() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.background = element_rect(fill = "white", colour = "black", linewidth = 0.5, linetype = "solid"),
        legend.position = "top",  
        plot.margin = unit(c(0, 0, 0, 0), "null")
  )+
  guides(
    fill = guide_colourbar(
      title.position = "top", title.hjust = 0.5, frame.colour = "black", barwidth = 12,
      barheight = 1, order = 1,
      direction = "horizontal",  
      label.position = "bottom",  
      label.hjust = 0.5,  
      title.vjust = 1  
    )
  ) +
  ylab("Site") +
  xlab("Campaign") +
  scale_fill_viridis(name = "Alpha", direction = -1)
ggsave(FigI, file = file.path("Figures","FigureI.jpeg"),
       width = 19.2, height = 11.77, dpi = 300, units = "in",
       type = "cairo")

# Distribution and median of the three mortality metrics :
complet_mortality_metrics <- death_preds261 %>%
  full_join(mortality_initiation, by = c("Campaign","id_site"))%>%
  full_join(Alpha, by = c("Campaign","id_site"))

death_metric<-pivot_longer(complet_mortality_metrics,cols=c(MM,MI,alpha),
                           names_to="Mortality_indicators", values_to = "Value")

death_metric_median <- death_metric %>%
  group_by(Mortality_indicators) %>%
  summarise(median = median(Value), count = n()) %>%
  ungroup()

# Figure 5 : This is the figure 5 which is included in the datapaper
theme_graphic <- function(base_family = "sans", ...) {
  theme_bw(base_family = base_family, ...) +
    theme(
      panel.grid = element_blank(),
      legend.background = element_rect(color = NA, fill = NA),
      strip.text = element_text(size = 11),
      axis.title = element_text(size = 12),
      legend.title = element_text(size = 12),
      legend.key.height = unit(0.5, "cm"),
      legend.key.width = unit(0.5, "cm"))}

Fig5 <- death_metric %>%
  ggplot() +
  geom_density(aes(x = Value, fill = Mortality_indicators, after_stat(scaled)), alpha = 0.5) +
  scale_fill_viridis(discrete = TRUE) +
  facet_grid(~ Mortality_indicators, scales = "free") +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.5), expand = expansion(mult = c(0, 0))) +
  geom_vline(data = death_metric_median, aes(xintercept = median), color = "black", size = 1) +
  scale_colour_viridis(discrete = TRUE) +
  ylab("Scale density") +
  theme_bw() +
  theme(legend.position = "none", panel.grid = element_blank(), legend.background = element_rect(color = NA, fill = NA))
ggsave(Fig5, file = file.path("Figures","Figure5.jpeg"),
       width = 8, height = 6, dpi = 300, units = "in",
       type = "cairo")


#Export of the mortality_metric file in .csv
write.csv(complet_mortality_metrics, file=file.path("Data","new_datasets","mortality_metric.csv"), row.names = FALSE, quote = TRUE, na = "NA")
